baseURL = "https://tirthbal.in/"
languageCode = "en-us"
theme = "tale"
title = "Tirth Bal"

[menu]
  [[menu.header]]
    identifier = "about"
    name = "about"
    weight = 1
    url = "/about"
  [[menu.header]]
    identifier = "post"
    name = "post"
    weight = 0
    url = "/post"

